NODE_MODULES := ./node_modules
SRC_DIR := ./src
DIST_DIR := ./dist




# Start the production server
# start: $(NODE_MODULES)
# 	npm start

# Run in development mode
dev:
	npm run dev

clean:
	rm -rf $(DIST_DIR)
